'''SConstruct derived from parent directory
Documentation of LaTeX scanner class at
http://www.scons.org/doc/HTML/scons-api/SCons.Scanner.LaTeX.LaTeX-class.html

http://www.scons.org/wiki/LatexSupport
'''

Siads = Environment()
Siads.PDF('siads.tex')

Siads.Command(
    'bounds.pdf',
    'plot.py',
    'python3 plot.py --plot_bounds bounds.pdf'
    )

#---------------
# Local Variables:
# eval: (python-mode)
# End:
